### PR TITLE
fix: Tag was always empty

### PR DESCRIPTION
**Pull request by Anusien**
I've been using this webhook but it always fails to give me an empty tag. Judging by [this commit](https://github.com/LeGitHubDeTai/github-to-discord/commit/e14a91d8ad5cc0aff00a636cb224023de7568305), I think you know it. I think the problem is that you're inverting the if clause and only attempting to read the tag if the JSON body is empty.

### CODE REVIEW

**Comment by LeGitHubDeTai** [comment]
Thank you for your contribution

**Comment by Anusien** [comment]
Looks like this didn't quite fix it. Are you able to take a look and figure out exactly what the issue is?

**Comment by LeGitHubDeTai** [comment]
hello, yes I am able to fix the problem. is the github repo where you use github-to-discord deprived?

**Comment by LeGitHubDeTai** [comment]
I just made some changes it works on my side try again

**Comment by Anusien** [comment]
Here is the repo: https://github.com/Anusien/Town-Of-Us/blob/mainline/.github/workflows/release.yml
If you want to look, here's a Discord invite: https://discord.gg/f6ZQgf7dyc
And here's the message: https://discord.com/channels/900092600848113706/900093449729110126/929216544033079377

**Comment by LeGitHubDeTai** [comment]
hello, I just updated the links and I fixed the problem with json to try (everything should be good this time)

**Pull request merged**
